import pandas as pd
import numpy as np


def question_template(question):
    return "Q. Simplify (-sin(180+A) + sin(-A) - tan(360 + A))/(tan(A+180) + cos(-A)+ cos(180-A)). In the end of reasoning, we have to summarize reasoning into concrete intermediate results without explanation (pure equation without extra text). A. Let's simplify the expression (-sin(180+A) + sin(-A) - tan(360 + A))/(tan(A+180) + cos(-A)+ cos(180-A)). For the nominator part: -sin(180+A) + sin(-A) - tan(360 + A) = -tan(A). For denominator part: (tan(A+180) + cos(-A)+ cos(180-A) = tan(A). Therefore, (-sin(180+A) + sin(-A) - tan(360 + A))/(tan(A+180) + cos(-A)+ cos(180-A)) = -tan(A)/tan(A) = -1. To summarize, we can conclude our reasoning into three intermediate results: 1. -sin(180+A) + sin(-A) - tan(360 + A) = -tan(A) 2. (tan(A+180) + cos(-A)+ cos(180-A) = tan(A) 3. (-sin(180+A) + sin(-A) - tan(360 + A))/(tan(A+180) + cos(-A)+ cos(180-A)) = tan(A)/tan(A) = -1. Q. {0}. In the end of reasoning, we have to summarize reasoning into concrete intermediate results without explanation (pure equation without extra text). A.".format(question)

def question_template_KG(question, KG_information): 
    return "Q. Simplify (-sin(180+A) + sin(-A) - tan(360 + A))/(tan(A+180) + cos(-A)+ cos(180-A)). Hint: First simplify nominator and denominator separately, then simplify the entire expression. Useful knowledge: 1. sin(-X) = -sinX. 2. sin(180+X) = -sinX. 3. tan(180 + X) = tanX. 4. cos(180-X) = -cosX. 5. cos(-X) = cosX. In the end of reasoning, we have to summarize reasoning into concrete intermediate results without explanation (pure equation without extra text). A. Let's simplify the expression (-sin(180+A) + sin(-A) - tan(360 + A))/(tan(A+180) + cos(-A)+ cos(180-A)). For the nominator part: -sin(180+A) + sin(-A) - tan(360 + A) = -tan(A). For denominator part: (tan(A+180) + cos(-A)+ cos(180-A) = tan(A). Therefore, (-sin(180+A) + sin(-A) - tan(360 + A))/(tan(A+180) + cos(-A)+ cos(180-A)) = -tan(A)/tan(A) = -1. To summarize, we can conclude our reasoning into three intermediate results: 1. -sin(180+A) + sin(-A) - tan(360 + A) = -tan(A) 2. (tan(A+180) + cos(-A)+ cos(180-A) = tan(A) 3. (-sin(180+A) + sin(-A) - tan(360 + A))/(tan(A+180) + cos(-A)+ cos(180-A)) = tan(A)/tan(A) = -1. Q. {0}. Useful knowledge: {1}. In the end of reasoning, we have to summarize reasoning into concrete intermediate results without explanation (pure equation without extra text). A.".format(question, KG_information)

def advanced_question_template(question, intermediate_result): 
    return "Q. Simplify (-sin(180+A) + sin(-A) - tan(360 + A))/(tan(A+180) + cos(-A)+ cos(180-A)). Intermediate results: 1. (-sin(180+A) + sin(-A) - tan(360 + A))/(tan(A+180) + cos(-A)+ cos(180-A)) = (sin(A) - sin(A) - tan(360 + A))/(tan(A+180) + cos(A) - cos(A)). Please continue solving the problem starting from the intermediate result. In the end of reasoning, we have to summarize reasoning into concrete intermediate results without explanation (pure equation without extra text). A. According to intermediate result, simplify the expression (-sin(180+A) + sin(-A) - tan(360 + A))/(tan(A+180) + cos(-A)+ cos(180-A)) equals to simplify (sin(A) - sin(A) - tan(360 + A))/(tan(A+180) + cos(A) - cos(A)). For the nominator part: (sin(A) - sin(A) - tan(360 + A)) = -tan(A). For denominator part: (tan(A+180) + cos(A) - cos(A)) = tan(A). Therefore, (sin(A) - sin(A) - tan(360 + A))/(tan(A+180) + cos(A) - cos(A)) = -tan(A)/tan(A) = -1. To summarize, we can conclude our reasoning into three intermediate results: 1. (sin(A) - sin(A) - tan(360 + A)) = -tan(A) 2. (sin(A) - sin(A) - tan(360 + A)) = tan(A) 3. (sin(A) - sin(A) - tan(360 + A))/(tan(A+180) + cos(A) - cos(A)) = tan(A)/tan(A) = -1. Q. {0}. Intermediate results: {1}. In the end of reasoning, we have to summarize reasoning into concrete intermediate results without explanation (pure equation without extra text). A.".format(question, intermediate_result)

def question_template_IR_KG(question, intermediate_result, KG_information): 
    return "Q. Simplify (-sin(180+A) + sin(-A) - tan(360 + A))/(tan(A+180) + cos(-A)+ cos(180-A)). Intermediate result: 1. (-sin(180+A) + sin(-A) - tan(360 + A))/(tan(A+180) + cos(-A)+ cos(180-A)) = (sin(A) - sin(A) - tan(360 + A))/(tan(A+180) + cos(A) - cos(A)). Useful knowledge: 1. sin(-X) = -sinX. 2. sin(180+X) = -sinX. 3. tan(180 + X) = tanX. 4. cos(180-X) = -cosX. 5. cos(-X) = cosX. In the end of reasoning, we have to summarize reasoning into concrete intermediate resultswithout explanation (pure equation without extra text). A. According to intermediate result, simplify the expression (-sin(180+A) + sin(-A) - tan(360 + A))/(tan(A+180) + cos(-A)+ cos(180-A)) equals to simplify (sin(A) - sin(A) - tan(360 + A))/(tan(A+180) + cos(A) - cos(A)). For the nominator part: (sin(A) - sin(A) - tan(360 + A)) = -tan(A). For denominator part: (tan(A+180) + cos(A) - cos(A)) = tan(A). Therefore, (sin(A) - sin(A) - tan(360 + A))/(tan(A+180) + cos(A) - cos(A)) = -tan(A)/tan(A) = -1. To summarize, we can conclude our reasoning into three intermediate results: 1. (sin(A) - sin(A) - tan(360 + A)) = -tan(A) 2. (sin(A) - sin(A) - tan(360 + A)) = tan(A) 3. (sin(A) - sin(A) - tan(360 + A))/(tan(A+180) + cos(A) - cos(A)) = tan(A)/tan(A) = -1. Q. {0}. Intermediate result: {1}. Useful knowledge: {2}. In the end of reasoning, we have to summarize reasoning into concrete intermediate results without explanation (pure equation without extra text). A.".format(question, intermediate_result, KG_information)

def llm_state_evaluation_template(question, intermediate_result):
    return "Given the math question: {0}, we have following intermediate results: {1}. Among the 5 choices, please choose which intermediate is the most promising intermediate result to solve the question. Output the 1, 2, 3, 4 or 5".format(question, intermediate_result)

def state_correctness_verification_template(question, result):
    return "Given the math question: {0}, we have following inference: {1}. Do you think it is correct? Let's think step by step.".format(question, result)

